=== api-evangelist/discogs/json-schema/discogs-release-version-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/discogs/refs/heads/main/json-schema/discogs-release-version-schema.json",
  "title": "ReleaseVersion",
  "description": "ReleaseVersion schema from Discogs API",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "resource_url": {
      "type": "string",
      "format": "uri"
    },
    "status": {
      "type": "string"
    },
    "thumb": {
      "type": "string",
      "format": "uri"
    },
    "format": {
      "type": "string"
    },
    "country": {
      "type": "string",
      "nullable": true
    },
    "title": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "released": {
      "type": "string"
    },
    "major_formats": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "catno": {
      "type": "string",
      "nullable": true
    },
    "stats": {
      "type": "object",
      "properties": {
        "community": {
          "type": "object",
          "properties": {
            "in_collection": {
              "type": "integer"
            },
            "in_wantlist": {
              "type": "integer"
            }
          }
        }
      }
    }
  }
}

=== api-evangelist/discogs/examples/discogs-release-version-example.json
{
  "id": 249504,
  "resource_url": "https://api.discogs.com/releases/249504",
  "status": "string-value",
  "thumb": "https://api.discogs.com/releases/249504",
  "format": "string-value",
  "country": "string-value",
  "title": "Kind Of Blue",
  "label": "string-value",
  "released": "string-value",
  "major_formats": [
    "string-value"
  ],
  "catno": "string-value",
  "stats": {
    "community": {
      "in_collection": 1,
      "in_wantlist": 1
    }
  }
}
