=== api-evangelist/discogs/json-schema/discogs-label-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/discogs/refs/heads/main/json-schema/discogs-label-schema.json",
  "title": "Label",
  "description": "Represents a label, company, recording studio, etc.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "readOnly": true
    },
    "name": {
      "type": "string"
    },
    "resource_url": {
      "type": "string",
      "format": "uri",
      "readOnly": true
    },
    "uri": {
      "type": "string",
      "format": "uri",
      "readOnly": true
    },
    "releases_url": {
      "type": "string",
      "format": "uri"
    },
    "profile": {
      "type": "string",
      "nullable": true
    },
    "contact_info": {
      "type": "string",
      "nullable": true
    },
    "parent_label": {
      "$ref": "#/components/schemas/LabelSummary",
      "nullable": true
    },
    "sublabels": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/LabelSummary"
      }
    },
    "urls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "images": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Image"
      }
    },
    "data_quality": {
      "type": "string"
    }
  }
}

=== api-evangelist/discogs/examples/discogs-label-example.json
{
  "id": 249504,
  "name": "Kind Of Blue",
  "resource_url": "https://api.discogs.com/releases/249504",
  "uri": "https://api.discogs.com/releases/249504",
  "releases_url": "https://api.discogs.com/releases/249504",
  "profile": "string-value",
  "contact_info": "string-value",
  "parent_label": {
    "id": 249504,
    "name": "Kind Of Blue",
    "resource_url": "https://api.discogs.com/releases/249504",
    "catno": "string-value",
    "entity_type": "string-value"
  },
  "sublabels": [
    {
      "id": {},
      "name": {},
      "resource_url": {},
      "catno": {},
      "entity_type": {}
    }
  ],
  "urls": [
    "https://api.discogs.com/releases/249504"
  ],
  "images": [
    {
      "type": {},
      "uri": {},
      "resource_url": {},
      "uri150": {},
      "width": {},
      "height": {}
    }
  ],
  "data_quality": "string-value"
}
