=== api-evangelist/discogs/json-schema/discogs-release-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/discogs/refs/heads/main/json-schema/discogs-release-summary-schema.json",
  "title": "ReleaseSummary",
  "description": "ReleaseSummary schema from Discogs API",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "year": {
      "type": "integer"
    },
    "resource_url": {
      "type": "string",
      "format": "uri"
    },
    "thumb": {
      "type": "string",
      "format": "uri"
    },
    "cover_image": {
      "type": "string",
      "format": "uri"
    },
    "formats": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ReleaseFormat"
      }
    },
    "labels": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/LabelSummary"
      }
    },
    "artists": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ArtistSummary"
      }
    },
    "genres": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "styles": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== api-evangelist/discogs/examples/discogs-release-summary-example.json
{
  "id": 249504,
  "title": "Kind Of Blue",
  "year": 1959,
  "resource_url": "https://api.discogs.com/releases/249504",
  "thumb": "https://api.discogs.com/releases/249504",
  "cover_image": "https://api.discogs.com/releases/249504",
  "formats": [
    {
      "name": {},
      "qty": {},
      "text": {},
      "descriptions": {}
    }
  ],
  "labels": [
    {
      "id": {},
      "name": {},
      "resource_url": {},
      "catno": {},
      "entity_type": {}
    }
  ],
  "artists": [
    {
      "id": {},
      "name": {},
      "resource_url": {},
      "anv": {},
      "join": {},
      "role": {},
      "tracks": {}
    }
  ],
  "genres": [
    "string-value"
  ],
  "styles": [
    "string-value"
  ]
}
