=== api-evangelist/discogs/json-schema/discogs-want-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/discogs/refs/heads/main/json-schema/discogs-want-schema.json",
  "title": "Want",
  "description": "Want schema from Discogs API",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "resource_url": {
      "type": "string",
      "format": "uri"
    },
    "rating": {
      "type": "integer"
    },
    "notes": {
      "type": "string",
      "nullable": true
    },
    "basic_information": {
      "$ref": "#/components/schemas/ReleaseSummary"
    }
  }
}

=== api-evangelist/discogs/examples/discogs-want-example.json
{
  "id": 249504,
  "resource_url": "https://api.discogs.com/releases/249504",
  "rating": 1,
  "notes": "string-value",
  "basic_information": {
    "id": 249504,
    "title": "Kind Of Blue",
    "year": 1959,
    "resource_url": "https://api.discogs.com/releases/249504",
    "thumb": "https://api.discogs.com/releases/249504",
    "cover_image": "https://api.discogs.com/releases/249504",
    "formats": [
      {}
    ],
    "labels": [
      {}
    ],
    "artists": [
      {}
    ],
    "genres": [
      {}
    ],
    "styles": [
      {}
    ]
  }
}
