=== api-evangelist/discogs/json-schema/discogs-order-message-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/discogs/refs/heads/main/json-schema/discogs-order-message-schema.json",
  "title": "OrderMessage",
  "description": "A message attached to a marketplace order.",
  "type": "object",
  "properties": {
    "refund": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "order": {
          "type": "object"
        }
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "message": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "message",
        "status",
        "shipping"
      ]
    },
    "order": {
      "type": "object",
      "properties": {
        "resource_url": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "subject": {
      "type": "string"
    },
    "from": {
      "$ref": "#/components/schemas/UserSummary"
    }
  }
}

=== api-evangelist/discogs/examples/discogs-order-message-example.json
{
  "refund": {
    "amount": 1.0,
    "order": {}
  },
  "timestamp": "2026-03-15T14:30:00Z",
  "message": "string-value",
  "type": "message",
  "order": {
    "resource_url": "https://api.discogs.com/releases/249504",
    "id": "string-value"
  },
  "subject": "string-value",
  "from": {
    "id": 249504,
    "username": "rodneyfool",
    "resource_url": "https://api.discogs.com/releases/249504"
  }
}
