=== api-evangelist/discogs/json-schema/discogs-community-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/discogs/refs/heads/main/json-schema/discogs-community-schema.json",
  "title": "Community",
  "description": "Community schema from Discogs API",
  "type": "object",
  "properties": {
    "have": {
      "type": "integer"
    },
    "want": {
      "type": "integer"
    },
    "rating": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "average": {
          "type": "number",
          "format": "float"
        }
      }
    },
    "submitter": {
      "$ref": "#/components/schemas/UserSummary"
    },
    "contributors": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/UserSummary"
      }
    },
    "data_quality": {
      "type": "string"
    },
    "status": {
      "type": "string"
    }
  }
}

=== api-evangelist/discogs/examples/discogs-community-example.json
{
  "have": 1,
  "want": 1,
  "rating": {
    "count": 42,
    "average": 4.32
  },
  "submitter": {
    "id": 249504,
    "username": "rodneyfool",
    "resource_url": "https://api.discogs.com/releases/249504"
  },
  "contributors": [
    {
      "id": {},
      "username": {},
      "resource_url": {}
    }
  ],
  "data_quality": "string-value",
  "status": "string-value"
}
